services:
  postgres:
    container_name: nest-api-pg
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=nest-api
    volumes:
      - ./data/pg:/data/postgres

  keycloak:
    image: keycloak/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=pg
    ports:
      - 8080:8080

  cache:
    container_name: nest-api-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
